export const statusCodeConst = [
  { code: 100, status: 'Continue' },
  { code: 101, status: 'Switching Protocols' },
  { code: 200, status: 'OK' },
  { code: 201, status: 'Created' },
  { code: 202, status: 'Accepted' },
  { code: 203, status: 'Non-Authoritative Information' },
  { code: 204, status: 'No Content' },
  { code: 205, status: 'Reset Content' },
  { code: 206, status: 'Partial Content' },
  { code: 300, status: 'Multiple Choices' },
  { code: 301, status: 'Moved Permanently' },
  { code: 302, status: 'Found' },
  { code: 303, status: 'See Other' },
  { code: 304, status: 'Not Modified' },
  { code: 305, status: 'Use Proxy' },
  { code: 307, status: 'Temporary Redirect' },
  { code: 400, status: 'Bad Request' },
  { code: 401, status: 'Unauthorized' },
  { code: 402, status: 'Payment Required' },
  { code: 403, status: 'Forbidden' },
  { code: 404, status: 'Not Found' },
  { code: 405, status: 'Method Not Allowed' },
  { code: 406, status: 'Not Acceptable' },
  { code: 407, status: 'Proxy Authentication Required' },
  { code: 408, status: 'Request Timeout' },
  { code: 409, status: 'Conflict' },
  { code: 410, status: 'Gone' },
  { code: 411, status: 'Length Required' },
  { code: 412, status: 'Precondition Failed' },
  { code: 413, status: 'Payload Too Large' },
  { code: 414, status: 'URI Too Long' },
  { code: 415, status: 'Unsupported Media Type' },
  { code: 416, status: 'Range Not Satisfiable' },
  { code: 417, status: 'Expectation Failed' },
  { code: 500, status: 'Internal Server Error' },
  { code: 501, status: 'Not Implemented' },
  { code: 502, status: 'Bad Gateway' },
  { code: 503, status: 'Service Unavailable' },
  { code: 504, status: 'Gateway Timeout' },
  { code: 505, status: 'HTTP Version Not Supported' },
];
